{{- range .Values.redisClusters }}
{{- if .externalAccess }}
{{- if .externalAccess.enabled }}
---
# ==============================================================================
# External LoadBalancer Service for {{ .name }}
# ==============================================================================
# Provides external access to Redis cluster via shared public IP
# All Redis clusters share the same IP with different ports
# Shared IP: {{ $.Values.externalAccess.sharedIP }}
# This cluster uses port: {{ .externalAccess.port }}
# ==============================================================================
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-external
  namespace: {{ .namespace }}
  labels:
    app.kubernetes.io/name: {{ .name }}
    app.kubernetes.io/component: redis-external
    redis-cluster: {{ .name }}
    connection-type: external
    {{- if .labels }}
    {{- toYaml .labels | nindent 4 }}
    {{- end }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .externalAccess.syncWave | default "1" | quote }}

    # external-dns configuration - automatically creates DNS record
    external-dns.alpha.kubernetes.io/hostname: {{ .externalAccess.hostname | default (printf "%s.pnats.cloud" .name) }}
    external-dns.alpha.kubernetes.io/ttl: "300"

    # MetalLB configuration - SHARED IP for all Redis clusters
    metallb.universe.tf/address-pool: public-pool
    # NOTE: Do not set both `metallb.io/loadBalancerIPs` (or legacy `metallb.universe.tf/loadBalancerIPs`)
    # and `spec.loadBalancerIP` on the same Service. MetalLB will reject it with:
    # "service can not have both metallb.io/loadBalancerIPs and svc.Spec.LoadBalancerIP".

    # Prometheus metrics scraping
    prometheus.io/scrape: "true"
    prometheus.io/port: "9121"

    # Description
    service.kubernetes.io/description: "Redis {{ .name }} - External endpoint on shared IP port {{ .externalAccess.port }}"

    {{- if .externalAccess.annotations }}
    {{- toYaml .externalAccess.annotations | nindent 4 }}
    {{- end }}
spec:
  type: LoadBalancer
  loadBalancerIP: {{ $.Values.externalAccess.sharedIP }}

  # Security: Restrict access to specific source IPs
  {{- if .externalAccess.allowedSourceRanges }}
  loadBalancerSourceRanges:
  {{- range .externalAccess.allowedSourceRanges }}
  - {{ . }}
  {{- end }}
  {{- else if $.Values.externalAccess.allowedSourceRanges }}
  loadBalancerSourceRanges:
  {{- range $.Values.externalAccess.allowedSourceRanges }}
  - {{ . }}
  {{- end }}
  {{- end }}

  externalTrafficPolicy: {{ .externalAccess.externalTrafficPolicy | default "Local" }}
  sessionAffinity: {{ .externalAccess.sessionAffinity | default "ClientIP" }}
  {{- if eq (.externalAccess.sessionAffinity | default "ClientIP") "ClientIP" }}
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: {{ .externalAccess.sessionAffinityTimeout | default 10800 }}
  {{- end }}

  # Selector matches Redis master and replica pods
  selector:
    app.kubernetes.io/name: {{ .name }}
    redis_setup_type: replication

  ports:
  - name: redis-client
    port: {{ .externalAccess.port }}
    targetPort: 6379
    protocol: TCP
  {{- if .externalAccess.sentinelPort }}
  - name: redis-sentinel
    port: {{ .externalAccess.sentinelPort }}
    targetPort: 26379
    protocol: TCP
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
