{{- range .Values.redisClusters }}
{{- if .auth }}
{{- if .auth.enabled }}
---
# ==============================================================================
# Password Generator for {{ .name }}
# ==============================================================================
# Uses External Secrets Password generator to create secure random passwords
# ==============================================================================
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: {{ .name }}-password-generator
  namespace: {{ .namespace }}
  labels:
    app.kubernetes.io/name: {{ .name }}
    app.kubernetes.io/component: redis-password-generator
    app.kubernetes.io/part-of: platform-data
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  length: {{ .auth.passwordLength | default 32 }}
  digits: {{ .auth.passwordDigits | default 8 }}
  symbols: {{ .auth.passwordSymbols | default 0 }}
  symbolCharacters: "!@#$%^&*"
  noUpper: false
  allowRepeat: true
---
# ==============================================================================
# ExternalSecret to generate Redis password Secret
# ==============================================================================
# Uses the Password generator to create a Kubernetes Secret
# ==============================================================================
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .name }}-password
  namespace: {{ .namespace }}
  labels:
    app.kubernetes.io/name: {{ .name }}
    app.kubernetes.io/component: redis-password
    app.kubernetes.io/part-of: platform-data
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: "0"  # Generate once, don't refresh
  target:
    name: {{ .name }}-password
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        password: "{{ `{{ .password }}` }}"
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: {{ .name }}-password-generator
{{- end }}
{{- end }}
{{- end }}
