{{- range .Values.redisClusters }}
{{- if .auth }}
{{- if .auth.enabled }}
{{- if .auth.pushToVault }}
{{- if .auth.pushToVault.enabled }}
---
# ==============================================================================
# PushSecret: Sync Redis password to Vault
# ==============================================================================
# Source: {{ .name }}-password secret in {{ .namespace }}
# Target: {{ .auth.pushToVault.vaultPath | default (printf "platform-data/redis/%s" .name) }}
# ==============================================================================
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: {{ .name }}-password-to-vault
  namespace: {{ .namespace }}
  labels:
    app.kubernetes.io/name: {{ .name }}
    app.kubernetes.io/component: redis-pushsecret
    app.kubernetes.io/part-of: platform-data
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: {{ .auth.pushToVault.refreshInterval | default "1h" }}
  deletionPolicy: None
  updatePolicy: Replace
  secretStoreRefs:
  - name: {{ .auth.pushToVault.secretStoreRef | default "vault-backend" }}
    kind: ClusterSecretStore
  selector:
    secret:
      name: {{ .name }}-password
  data:
  - conversionStrategy: None
    match:
      secretKey: password
      remoteRef:
        remoteKey: {{ .auth.pushToVault.vaultPath | default (printf "platform-data/redis/%s" .name) }}
        property: password
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
