# Terraform variables generated by the API CLI
global_config = {
  environment     = "development"
  resource_prefix = "pn-dev"
  proxmox_config = {
    endpoint  = "https://proxmox.dev.local:8006/api2/json"
    api_token = "CHANGE_ME"
    node_name = "pve-dev"
    datastore = "local-lvm"
  }
}

networking = {
  vlan_range_start = 200
  vlan_range_end   = 240
  gateway          = "192.168.106.1"
  dns_servers      = ["8.8.8.8","8.8.4.4"]
}

image_registry = {}
template_registry = {}
