---
# Kubernetes Cluster Inventory - Production Environment
# Migration from inventory.ini to hosts.yml format
#
# This inventory defines:
# - 4 control plane nodes (masters)
# - 3 etcd nodes (high availability)
# - 14 total worker nodes (4 masters + 10 dedicated workers)
#
# Network:
# - ansible_host: Management network (192.168.106.x)
# - ip/access_ip: Cluster network (192.168.102.x)

all:
  hosts:
    # Control Plane Nodes (Masters)
    k8s-master-01:
      ansible_host: 192.168.106.111
      ip: 192.168.102.111
      access_ip: 192.168.102.111
      etcd_member_name: etcd1

    k8s-master-02:
      ansible_host: 192.168.106.112
      ip: 192.168.102.112
      access_ip: 192.168.102.112
      etcd_member_name: etcd2

    k8s-master-03:
      ansible_host: 192.168.106.113
      ip: 192.168.102.113
      access_ip: 192.168.102.113
      etcd_member_name: etcd3

    k8s-master-04:
      ansible_host: 192.168.106.114
      ip: 192.168.102.114
      access_ip: 192.168.102.114

    # Dedicated Worker Nodes
    k8s-worker-01:
      ansible_host: 192.168.106.121
      ip: 192.168.102.121
      access_ip: 192.168.102.121

    k8s-worker-02:
      ansible_host: 192.168.106.122
      ip: 192.168.102.122
      access_ip: 192.168.102.122

    k8s-worker-03:
      ansible_host: 192.168.106.123
      ip: 192.168.102.123
      access_ip: 192.168.102.123

    k8s-worker-04:
      ansible_host: 192.168.106.124
      ip: 192.168.102.124
      access_ip: 192.168.102.124

    k8s-worker-05:
      ansible_host: 192.168.106.125
      ip: 192.168.102.125
      access_ip: 192.168.102.125

    k8s-worker-06:
      ansible_host: 192.168.106.126
      ip: 192.168.102.126
      access_ip: 192.168.102.126

    k8s-worker-07:
      ansible_host: 192.168.106.127
      ip: 192.168.102.127
      access_ip: 192.168.102.127

    k8s-worker-08:
      ansible_host: 192.168.106.128
      ip: 192.168.102.128
      access_ip: 192.168.102.128

    k8s-worker-09:
      ansible_host: 192.168.106.129
      ip: 192.168.102.129
      access_ip: 192.168.102.129

    k8s-worker-10:
      ansible_host: 192.168.106.130
      ip: 192.168.102.130
      access_ip: 192.168.102.130

  children:
    # Control plane nodes (API server, scheduler, controller manager)
    kube-master:
      hosts:
        k8s-master-01:
        k8s-master-02:
        k8s-master-03:
        k8s-master-04:

          # etcd cluster (distributed key-value store)
          # Using 3 nodes for quorum (minimum for HA)
    etcd:
      hosts:
        k8s-master-01:
        k8s-master-02:
        k8s-master-03:

          # Worker nodes (run application workloads)
          # Includes all masters (they can also run workloads) + dedicated workers
    kube-node:
      hosts:
        k8s-master-01:
        k8s-master-02:
        k8s-master-03:
        k8s-master-04:
        k8s-worker-01:
        k8s-worker-02:
        k8s-worker-03:
        k8s-worker-04:
        k8s-worker-05:
        k8s-worker-06:
        k8s-worker-07:
        k8s-worker-08:
        k8s-worker-09:
        k8s-worker-10:

          # Kubernetes cluster (combines control plane and workers)
    k8s_cluster:
      children:
        kube-master:
        kube-node:

          # Calico route reflector (empty - using Cilium instead)
    calico_rr:
      hosts: {}
