#!/bin/bash
echo "PNCP Kubespray Orchestrator"
echo "============================"
echo ""
echo "Available commands:"
echo "  - ansible-playbook (Kubespray deployment)"
echo "  - kubectl (Kubernetes client)"
echo "  - cilium (Cilium CLI)"
echo ""
echo "Example: ansible-playbook -i inventory/pn-production/hosts.yml cluster.yml -b"
echo ""
echo "Note: Helm and CNI installation scripts run on the host, not in this container."
echo ""
exec "$@"
