#!/bin/bash
echo "PNCP Kubespray Orchestrator"
echo "============================"
echo ""
echo "Available commands:"
echo "  - ansible-playbook (Kubespray deployment)"
echo "  - kubectl (Kubernetes client)"
echo "  - collect-non-os-disks (inventory non-OS disks)"
echo "  - ceph-force-disk-cleanup (DESTRUCTIVE disk wipe)"
echo "  - pn-k8s-tools-tests (Jest-like unittest runner)"
echo "  - cilium (Cilium CLI)"
echo ""
echo "Example: ansible-playbook -i inventory/pn-production/hosts.yml cluster.yml -b"
echo ""
echo "Note: Helm and CNI installation scripts run on the host, not in this container."
echo ""
exec "$@"
