{{- range .Values.pgClusters }}
{{- $tls := .tls | default dict }}
{{- $pooler := .pooler | default dict }}
{{- $poolerReplica := $pooler.replica | default dict }}
{{- if $tls.enabled }}
{{- $clusterDomain := ($.Values.clusterDomain | default "cluster.local") }}
{{- $privateKey := $tls.privateKey | default dict }}
{{- $defaultIssuerName := ($.Values.tls.issuerName | default "platform-internal-ca") }}
{{- $defaultIssuerKind := ($.Values.tls.issuerKind | default "ClusterIssuer") }}
---
# TLS Certificate for PostgreSQL Cluster: {{ .name }}
# Automatically provisions certificates via cert-manager
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .name }}-tls
  namespace: {{ .namespace }}
  labels:
    app.kubernetes.io/name: {{ .name }}
    app.kubernetes.io/component: database-tls
    app.kubernetes.io/managed-by: postgres-operator
    {{- if .labels }}
    {{- toYaml .labels | nindent 4 }}
    {{- end }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .tls.syncWave | default "-1" | quote }}
spec:
  # Secret name where certificate will be stored
  secretName: {{ .name }}-tls-cert

  # Certificate duration and renewal
  duration: {{ .tls.duration | default "2160h" }}  # 90 days
  renewBefore: {{ .tls.renewBefore | default "720h" }}  # 30 days before expiry

  # Subject configuration
  subject:
    organizations:
    - {{ .tls.organization | default "ProficientNow Cloud Platform" }}

  # Common name (primary DNS name)
  commonName: {{ .name }}.{{ .namespace }}.svc.{{ $clusterDomain }}

  # DNS names covered by this certificate
  dnsNames:
  # Master service
  - {{ .name }}.{{ .namespace }}.svc.{{ $clusterDomain }}
  - {{ .name }}.{{ .namespace }}.svc
  - {{ .name }}.{{ .namespace }}
  - {{ .name }}

  # Replica service
  - {{ .name }}-repl.{{ .namespace }}.svc.{{ $clusterDomain }}
  - {{ .name }}-repl.{{ .namespace }}.svc
  - {{ .name }}-repl.{{ .namespace }}

  {{- if ($pooler.enabled | default false) }}
  # Connection pooler services
  - {{ .name }}-pooler.{{ .namespace }}.svc.{{ $clusterDomain }}
  - {{ .name }}-pooler.{{ .namespace }}.svc
  - {{ .name }}-pooler.{{ .namespace }}
  {{- if ($poolerReplica.enabled | default false) }}
  - {{ .name }}-pooler-repl.{{ .namespace }}.svc.{{ $clusterDomain }}
  - {{ .name }}-pooler-repl.{{ .namespace }}.svc
  - {{ .name }}-pooler-repl.{{ .namespace }}
  {{- end }}
  {{- end }}

  {{- if $tls.additionalDNSNames }}
  # Additional DNS names (e.g., external load balancer)
  {{- range $tls.additionalDNSNames }}
  - {{ . }}
  {{- end }}
  {{- end }}

  # IP addresses (if needed for direct IP access)
  {{- if $tls.ipAddresses }}
  ipAddresses:
  {{- range $tls.ipAddresses }}
  - {{ . }}
  {{- end }}
  {{- end }}

  # Issuer reference
  issuerRef:
    {{- if $tls.issuerRef }}
    name: {{ $tls.issuerRef.name }}
    kind: {{ $tls.issuerRef.kind | default "ClusterIssuer" }}
    {{- if $tls.issuerRef.group }}
    group: {{ $tls.issuerRef.group }}
    {{- end }}
    {{- else }}
    # Default to cluster-wide issuer from `.Values.tls.*`
    name: {{ $tls.issuer | default $defaultIssuerName }}
    kind: {{ $tls.issuerKind | default $defaultIssuerKind }}
    {{- end }}

  # Secret template - format for PostgreSQL compatibility
  secretTemplate:
    labels:
      app.kubernetes.io/name: {{ .name }}
      app.kubernetes.io/component: database-tls
      postgres-cluster: {{ .name }}
    annotations:
      platform.pnats.cloud/certificate-name: {{ .name }}-tls
      platform.pnats.cloud/common-name: {{ .name }}.{{ .namespace }}.svc.{{ $clusterDomain }}

  # Key settings
  privateKey:
    algorithm: {{ $privateKey.algorithm | default "RSA" }}
    {{- if eq ($privateKey.algorithm | default "RSA") "RSA" }}
    size: {{ $privateKey.size | default 2048 }}
    {{- else if eq ($privateKey.algorithm | default "RSA") "ECDSA" }}
    size: {{ $privateKey.size | default 256 }}
    {{- end }}
    encoding: {{ $privateKey.encoding | default "PKCS1" }}
    rotationPolicy: {{ $privateKey.rotationPolicy | default "Always" }}

  # Key usages
  usages:
  - server auth
  - client auth
  - digital signature
  - key encipherment

  {{- if $tls.isCA }}
  # If this is a CA certificate
  isCA: true
  {{- end }}

{{- end }}
{{- end }}
