{{- range .Values.pgClusters }}
{{- if .externalAccess }}
{{- if .externalAccess.enabled }}
{{- $pooler := .pooler | default dict }}
{{- $poolerEnabled := $pooler.enabled | default true }}
---
# ==============================================================================
# External LoadBalancer Services for {{ .name }}
# ==============================================================================
# Provides external access to PostgreSQL via SHARED public IPs (different ports)
# All databases share 3 IPs total:
#   - Write: {{ $.Values.externalAccess.sharedIPs.write }} (all write endpoints, different ports)
#   - Read:  {{ $.Values.externalAccess.sharedIPs.read }} (all read endpoints, different ports)
#   - Admin: {{ $.Values.externalAccess.sharedIPs.admin }} (all admin endpoints, different ports)
# This database uses port: {{ .externalAccess.port }}
# Three service types per cluster:
#   1. Write (master + pooler): For transactional writes
#   2. Read (replica + pooler): For transactional reads (load balanced)
#   3. Admin (master direct): For migrations and maintenance (no pooling)
# ==============================================================================

{{- if .externalAccess.write }}
{{- if .externalAccess.write.enabled }}
---
# Write Service - Master with Connection Pooler (Transaction Mode)
# Use this for: Application writes, transactional operations
# Connection: {{ .externalAccess.write.hostname | default (printf "%s-write.pnats.cloud" .name) }}:{{ .externalAccess.port }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-external-write
  namespace: {{ .namespace }}
  labels:
    app.kubernetes.io/name: {{ .name }}
    app.kubernetes.io/component: database-external-write
    postgres-cluster: {{ .name }}
    connection-type: write-pooled
    {{- if .labels }}
    {{- toYaml .labels | nindent 4 }}
    {{- end }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .externalAccess.syncWave | default "1" | quote }}

    # external-dns configuration
    external-dns.alpha.kubernetes.io/hostname: {{ .externalAccess.write.hostname | default (printf "%s-write.pnats.cloud" .name) }}
    external-dns.alpha.kubernetes.io/ttl: "300"

    # MetalLB configuration - SHARED IP for all write endpoints
    metallb.universe.tf/address-pool: public-pool
    metallb.universe.tf/loadBalancerIPs: {{ $.Values.externalAccess.sharedIPs.write }}
    metallb.universe.tf/allow-shared-ip: pn-pg-write

    # Description
    service.kubernetes.io/description: "PostgreSQL {{ .name }} - Write endpoint (pooled) on shared IP port {{ .externalAccess.port }}"

    {{- if .externalAccess.write.annotations }}
    {{- toYaml .externalAccess.write.annotations | nindent 4 }}
    {{- end }}
spec:
  type: LoadBalancer
  loadBalancerIP: {{ $.Values.externalAccess.sharedIPs.write }}

  # Security: Restrict access to specific source IPs
  {{- if .externalAccess.write.allowedSourceRanges }}
  loadBalancerSourceRanges:
  {{- range .externalAccess.write.allowedSourceRanges }}
  - {{ . }}
  {{- end }}
  {{- else if .externalAccess.allowedSourceRanges }}
  loadBalancerSourceRanges:
  {{- range .externalAccess.allowedSourceRanges }}
  - {{ . }}
  {{- end }}
  {{- end }}

  externalTrafficPolicy: {{ .externalAccess.write.externalTrafficPolicy | default "Local" }}
  sessionAffinity: {{ .externalAccess.write.sessionAffinity | default "ClientIP" }}
  {{- if eq (.externalAccess.write.sessionAffinity | default "ClientIP") "ClientIP" }}
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: {{ .externalAccess.write.sessionAffinityTimeout | default 10800 }}
  {{- end }}

  selector:
    application: spilo
    cluster-name: {{ .name }}
    spilo-role: master

  ports:
  - name: postgresql
    port: {{ .externalAccess.port }}
    targetPort: {{ $poolerEnabled | ternary "pgbouncer" "postgresql" }}
    protocol: TCP
{{- end }}
{{- end }}

{{- if .externalAccess.read }}
{{- if .externalAccess.read.enabled }}
---
# Read Service - Replicas with Connection Pooler (Transaction Mode)
# Use this for: Application reads, analytics, reporting
# Connection: {{ .externalAccess.read.hostname | default (printf "%s-read.pnats.cloud" .name) }}:{{ .externalAccess.port }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-external-read
  namespace: {{ .namespace }}
  labels:
    app.kubernetes.io/name: {{ .name }}
    app.kubernetes.io/component: database-external-read
    postgres-cluster: {{ .name }}
    connection-type: read-pooled
    {{- if .labels }}
    {{- toYaml .labels | nindent 4 }}
    {{- end }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .externalAccess.syncWave | default "1" | quote }}

    # external-dns configuration
    external-dns.alpha.kubernetes.io/hostname: {{ .externalAccess.read.hostname | default (printf "%s-read.pnats.cloud" .name) }}
    external-dns.alpha.kubernetes.io/ttl: "300"

    # MetalLB configuration - SHARED IP for all read endpoints
    metallb.universe.tf/address-pool: public-pool
    metallb.universe.tf/loadBalancerIPs: {{ $.Values.externalAccess.sharedIPs.read }}
    metallb.universe.tf/allow-shared-ip: pn-pg-read

    # Description
    service.kubernetes.io/description: "PostgreSQL {{ .name }} - Read endpoint (pooled) on shared IP port {{ .externalAccess.port }}"

    {{- if .externalAccess.read.annotations }}
    {{- toYaml .externalAccess.read.annotations | nindent 4 }}
    {{- end }}
spec:
  type: LoadBalancer
  loadBalancerIP: {{ $.Values.externalAccess.sharedIPs.read }}

  # Security: Restrict access to specific source IPs
  {{- if .externalAccess.read.allowedSourceRanges }}
  loadBalancerSourceRanges:
  {{- range .externalAccess.read.allowedSourceRanges }}
  - {{ . }}
  {{- end }}
  {{- else if .externalAccess.allowedSourceRanges }}
  loadBalancerSourceRanges:
  {{- range .externalAccess.allowedSourceRanges }}
  - {{ . }}
  {{- end }}
  {{- end }}

  externalTrafficPolicy: {{ .externalAccess.read.externalTrafficPolicy | default "Local" }}
  sessionAffinity: {{ .externalAccess.read.sessionAffinity | default "None" }}

  selector:
    application: spilo
    cluster-name: {{ .name }}
    spilo-role: replica

  ports:
  - name: postgresql
    port: {{ .externalAccess.port }}
    targetPort: {{ $poolerEnabled | ternary "pgbouncer" "postgresql" }}
    protocol: TCP
{{- end }}
{{- end }}

{{- if .externalAccess.admin }}
{{- if .externalAccess.admin.enabled }}
---
# Admin Service - Master Direct Connection (Session/Raw Mode)
# Use this for: Migrations, schema changes, pg_dump/restore, VACUUM, etc.
# Connection: {{ .externalAccess.admin.hostname | default (printf "%s-admin.pnats.cloud" .name) }}:{{ .externalAccess.port }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-external-admin
  namespace: {{ .namespace }}
  labels:
    app.kubernetes.io/name: {{ .name }}
    app.kubernetes.io/component: database-external-admin
    postgres-cluster: {{ .name }}
    connection-type: admin-direct
    {{- if .labels }}
    {{- toYaml .labels | nindent 4 }}
    {{- end }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .externalAccess.syncWave | default "1" | quote }}

    # external-dns configuration
    external-dns.alpha.kubernetes.io/hostname: {{ .externalAccess.admin.hostname | default (printf "%s-admin.pnats.cloud" .name) }}
    external-dns.alpha.kubernetes.io/ttl: "300"

    # MetalLB configuration - SHARED IP for all admin endpoints
    metallb.universe.tf/address-pool: public-pool
    metallb.universe.tf/loadBalancerIPs: {{ $.Values.externalAccess.sharedIPs.admin }}
    metallb.universe.tf/allow-shared-ip: pn-pg-admin

    # Description
    service.kubernetes.io/description: "PostgreSQL {{ .name }} - Admin endpoint (direct, no pooling) on shared IP port {{ .externalAccess.port }}"

    {{- if .externalAccess.admin.annotations }}
    {{- toYaml .externalAccess.admin.annotations | nindent 4 }}
    {{- end }}
spec:
  type: LoadBalancer
  loadBalancerIP: {{ $.Values.externalAccess.sharedIPs.admin }}

  # Security: STRICTLY restrict admin access
  {{- if .externalAccess.admin.allowedSourceRanges }}
  loadBalancerSourceRanges:
  {{- range .externalAccess.admin.allowedSourceRanges }}
  - {{ . }}
  {{- end }}
  {{- else if .externalAccess.allowedSourceRanges }}
  loadBalancerSourceRanges:
  {{- range .externalAccess.allowedSourceRanges }}
  - {{ . }}
  {{- end }}
  {{- else }}
  # Default: Block all external access if not explicitly allowed
  loadBalancerSourceRanges:
  - 0.0.0.0/32  # Block all by default - must configure allowedSourceRanges
  {{- end }}

  externalTrafficPolicy: {{ .externalAccess.admin.externalTrafficPolicy | default "Local" }}
  sessionAffinity: {{ .externalAccess.admin.sessionAffinity | default "ClientIP" }}
  {{- if eq (.externalAccess.admin.sessionAffinity | default "ClientIP") "ClientIP" }}
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: {{ .externalAccess.admin.sessionAffinityTimeout | default 10800 }}
  {{- end }}

  selector:
    application: spilo
    cluster-name: {{ .name }}
    spilo-role: master

  ports:
  - name: postgresql
    port: {{ .externalAccess.port }}
    targetPort: postgresql  # Direct PostgreSQL port, bypassing pooler
    protocol: TCP
{{- end }}
{{- end }}

{{- end }}
{{- end }}
{{- end }}
