{{- range .Values.pgClusters }}
{{- if .pushSecretsToVault }}
{{- if .pushSecretsToVault.enabled }}
{{- $cluster := . }}
{{- $vaultPathPrefix := .pushSecretsToVault.vaultPathPrefix | default "platform-data/postgres" }}
{{- $refreshInterval := .pushSecretsToVault.refreshInterval | default "1h" }}
{{- $secretStoreRef := .pushSecretsToVault.secretStoreRef | default "vault-backend" }}
{{- range $user := .pushSecretsToVault.users }}
---
# PushSecret: Sync Zalando postgres password to Vault
# Source: {{ $user }}.{{ $cluster.name }}.credentials.postgresql.acid.zalan.do
# Target: {{ $vaultPathPrefix }}/{{ $user }}
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: {{ $cluster.name }}-{{ $user }}-to-vault
  namespace: {{ $cluster.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  refreshInterval: {{ $refreshInterval }}
  secretStoreRefs:
  - name: {{ $secretStoreRef }}
    kind: ClusterSecretStore
  selector:
    secret:
      name: {{ $user }}.{{ $cluster.name }}.credentials.postgresql.acid.zalan.do
  data:
  - match:
      secretKey: password
      remoteRef:
        remoteKey: {{ $vaultPathPrefix }}/{{ $user }}
        property: password
  - match:
      secretKey: username
      remoteRef:
        remoteKey: {{ $vaultPathPrefix }}/{{ $user }}
        property: username
{{- end }}
{{- end }}
{{- end }}
{{- end }}
